Week4
XeniyaDob/node-express-course pull request #4
Opened 2024-03-16 15:09 UTC by XeniyaDob

This is a ***Draft PR*** until the previous PR is approved

- Understanding Middleware For Express
- Middleware Invocation Patterns
- Refactoring into Router and Controller Modules

2024-03-30 20:30 UTC, ddigioia3 requested changes
It looks like you may have broken the logger when you refactored everything into the traditional routers, controllers, middleware pattern.
Go ahead and fix that and this will be good to go.

2024-03-30 20:30 UTC, ddigioia3 commented on 02-express-tutorial/logger.js
> +  const date =
## Required Change
[Reinventing the Wheel + Code Readability + Standardization]
There are certain common tasks like formatting a date where its never a good idea to write your own code. When there is a standard way of doing it that other developers are going to be more familiar with, the code is automatically easier to understand and work with when that standard is used. There are a few common libraries used in node to handle date parsing, they are referenced in this [stack overflow post](https://stackoverflow.com/questions/10645994/how-to-format-a-utc-date-as-a-yyyy-mm-dd-hhmmss-string-using-nodejs). The [strftime](https://github.com/samsonjs/strftime) package and [dateformat](https://github.com/felixge/node-dateformat) use the most common pattern here where the `Date()` is passed with with a string like `yyyy-mm-dd h:MM:ss` to get a date like `2024-03-30 15:32:24`.


In this case, since the function is logging there is an even easier way to do this which is to just use [ISO time format](https://www.techtarget.com/whatis/definition/ISO-date-format). ISO time format is used a lot in programming and is the most common time format to see in logs as it has a lot of practical advantages such as:
1. automatically adjusting for timezone 
2. an alphabetical, string sort naturally sorts chronologically

The advantage of #1 is pretty self explanatory, but let me explain #2 in a bit more detail. When working with logs, its common to want to sort them chronologically. Since each line is a string it can be a challenge to actually get them sorted right. If the code uses a more common human format such as `mm-dd-yyyy` then `02-01-2023` would be treated as after `01-01-2024` despite the fact that it's actually 11 months earlier. This can cause some headaches. The iso date is `yyyy-mm-dd` is structured so that an alphabetical string sort still sorts it chronologically.

To use the isodate all you need to do is call the `toISOString()` method on the `Date()` class so:
```js
const dateTime = Date().toISOString();
```

2024-03-30 20:30 UTC, ddigioia3 commented on 02-express-tutorial/logger.js
> +  console.log(method, url, dateTime);
## Optional Improvement
[Readability and Standardization]
Typically logs put the date time first then the "level" of the log message (debug, info, warning, error, fatal), followed by the message itself.
This makes scrolling or parsing the logs a lot easier.

So here we might see `[2024-03-30T20:14:08Z] INFO - method POST called on http://localhost:3000/api/v1/person`.

You can easily do this with string interpolation to keep is readable:
```js
const logLevel = "INFO";
const msg = `method ${method} called on ${url}`;
console.log(`[${dateTime} ${logLevel} - ${msg}`);
```

2024-03-30 20:30 UTC, ddigioia3 commented on 02-express-tutorial/app.js
## Required Change
[Missing Requirement]
The Logger middleware is not actually used. It needs to be required in the app.js and then used by express.

2024-03-30 20:30 UTC, ddigioia3 commented on 02-express-tutorial/logger.js
## Optional Change
[File Structure + Standardization]
Since this is a middleware, typically it would be in the middleware folder.

2024-03-31 13:53 UTC, XeniyaDob commented
> It looks like you may have broken the logger when you refactored everything into the traditional routers, controllers, middleware pattern. Go ahead and fix that and this will be good to go.

Yeah, you're totally right. How could I delete such a great feature? Thanks for providing such helpful resources.

2024-04-01 23:06 UTC, ddigioia3 approved these changes

2024-04-02 13:12 UTC, merged